### ISSUE TITLE
GlobalRef for JMethodID

### ISSUE THREAD

**Issue by maxv-rust** [jni-rs/jni-rs#270] opened 2020-10-10 08:59 UTC
I have a question about jni-rs's architecture.

There is [JMethodID](https://docs.rs/jni/0.17.0/jni/objects/struct.JMethodID.html) struct which bounded to the lifetime.

* From my point of view it's not clear why it's bounded to lifetime? It looks like JMethodID can be safely saved and reused with another JNIEnv. I didn't found proof in the official documentation but it was covered as a part of [SO question](https://stackoverflow.com/questions/2093112/why-i-should-not-reuse-a-jclass-and-or-jmethodid-in-jni)
* Even if JMethodID has to be bounded, what should be the right way to create GlobalRef to reuse the same JMethodID multiple times?

Please let me know if I should you another way of communication for that kind of question.

Thank you in advance for your help.

**Comment by maxv-rust** [comment] 2020-10-11 00:19
It looks like `JMethodID` is not `Sync` as well :-(

**Comment by dmitry-timofeev** [comment] 2020-10-14 18:36
> I didn't found proof in the official documentation

I think this could work: https://docs.oracle.com/en/java/javase/11/docs/specs/jni/design.html#accessing-fields-and-methods 

> A field or method ID does not prevent the VM from unloading the class from which the ID has been derived. _After the class is unloaded, the method or field ID becomes invalid._

I.e., these IDs (pointers) are valid until the class is unloaded, which is not directly related to thread attachment (= `JNIEnv` lifetime).

> Even if JMethodID has to be bounded, what should be the right way to create GlobalRef to reuse the same JMethodID multiple times?

Please note that they are not JNI references to Java objects (like JObject/GlobalRef), hence they must not be used as such. To keep them alive beyond JNIEnv, you must keep the corresponding class alive with a GlobalRef.

> It looks like JMethodID is not Send/Sync as well :-(

It is a pointer type, and JVM must not restrict their usage from different threads: https://docs.oracle.com/en/java/javase/11/docs/specs/jni/types.html#field-and-method-ids 

If they have to be Send/Sync to use them safely (I am not an expert in Rust, @stanislav-tkach ?), then it must make sense to add that. I see Exonum JNI cache used some unsafe, though it is a thread-safe implementation that guarantees their visibility in any thread with Once: https://github.com/exonum/exonum-java-binding/blob/4e00cd8cbae198ac0e8a49cb1405092537f306bc/exonum-java-binding/core/rust/src/utils/jni_cache.rs#L209

**Comment by stanislav-tkach** [comment] 2020-10-15 20:28
If `JVM` doesn't restrict `JMethodID` from different threads, then `Send` and `Sync` implementations can be safely added (#274).

**Comment by georgwi** [comment] 2021-05-05 22:54
I would like to follow up on this:

It would be nice for my application to keep a `JMethodID` around between repeated calls to my rust function as that seems to speed up my library significantly. There is a very neat way in place with the `GlobalRef` for keeping objects around and removing the lifetime bounds so I can easily reuse them in Rust. However, for methods there is no such thing correct? Maybe I am missing a trick here. From @dmitry-timofeev's answer above I gather that it should be safe for me to do this:

```
let class = env.find_class("Ljava/lang/Object;").unwrap();
let method = env.get_method_id(class, "notify", "()V").unwrap();
let global_ref = env.new_global_ref(class).unwrap();
let global_method = JMethodID::from(method.into_inner());
```

My idea here is that I would keep both, the global reference to the class as well as my `global_method`, around together in some helper struct. This should prevent the class from being unloaded and the method ID from becoming invalid correct?

A follow up question: the last line in the snippet seems to me like a hacky way of removing the lifetime parameter from the method ID. Is there a better way to do this (assuming my approach is safe of course)? Could this be a future feature where maybe the creation of a global reference to a method could be streamlined? To simplify my own code I am using something like this:

```
pub struct GlobalMethodID {
    // TODO: can this be optimized away?
    _class: GlobalRef,
    method: JMethodID<'static>,
}

impl Deref for GlobalMethodID {
    type Target = JMethodID<'static>;

    fn deref(&self) -> &Self::Target {
        &self.method
    }
}

impl GlobalMethodID {
    pub fn try_new(env: &JNIEnv, class: &str, method: &str, signature: &str) -> Result<Self> {
        let class = env.find_class(class)?;
        let method = env.get_method_id(class, method, signature)?;
        Ok(Self {
            _class: env.new_global_ref(class)?,
            method: JMethodID::from(method.into_inner()),
        })
    }
}
```

Finally: from the link above to the JNI documentation it seems this should hold for fields just as it does for methods.

**Comment by rib** [comment] 2022-04-12 02:18
I found that this issue looks like a duplicate of (or at least closely related to) https://github.com/jni-rs/jni-rs/issues/38

**Closed** 2022-10-14 18:07 UTC
